### ISSUE TITLE
debug help needed. 

### ISSUE THREAD

**Issue by jacksnodgrass** [tedpearson/electric-usage-downloader#4]
Trying to get this to work with a different provider.... https://tcectexas.smarthub.coop - pretty sure it's the same backend code... pretty sure. My config.yaml has:
```
extract_days: 10
utility:
  api_url: https://tcectexas.smarthub.coop
  username: my-email
  password: my UNENCODED PASS ( from the oauth/v2 page... it's an unencoded password... )
  account: my-acct
  service_location: my-location
influxdb:
  host: https://localhost:8428
  auth_token: johndoe:influx_password
  database: db_name
  insecure: false
```

when I run: 
go run main.go --config config.yaml
Start date: 2024-02-25 00:00:00 -0600 CST
End date: 2024-03-05 23:59:00 -0600 CST
Authenticating with Novec API...
panic: auth response did not include auth token

goroutine 1 [running]:
main.main()
	/home/jack/electric-usage-downloader/main.go:9 +0x2b
exit status 2

any way to see if the code is sending the correct userid/passwd from the .yml file and what the actual packet send and received is? I no nothing about go....  a nice -Debug flag that showed the packets send and received would be really, really nice. 

The oath/v2 call in the browser when it works sends: 
userId=my-email&password=my-unencoded-pass
and gets: 

```
{
    "status": "SUCCESS",
    "authorizationToken": "really-long-auth-token",
    "username": "my-email-address",
    "expiration": 1709660527,
    "primaryUsername": "my-email-address",
    "isSecondaryRegistration": false,
    "expiresIn": 299
}
```

if that helps / matters...
